name: Deploy and run Docker Image
run-name: Deploy and run Docker Image [${{github.ref_name}}]
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploy and run Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker Image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.AWS_SSH_HOST}}
          username: ${{secrets.AWS_SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            container_id="$(docker container ls  | grep '${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_REPOSITORY}}' | awk '{print $1}')"
            if [ ! -z $container_id ]; then
              docker stop $container_id > /dev/null
            fi
            docker run -it -d -p 8001:8080 ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_REPOSITORY}}:${{github.ref_name}}

      - name: Wait for Docker Startup
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'

      - name: Check Website available
        run: |
          if ! curl --output /dev/null --silent --head --fail "${{vars.MONITORING_URI}}"; then
            exit 1
          fi
