name: Run Docker Image
run-name: Run Docker Image [${{github.ref_name}}]
on:
  workflow_dispatch:
jobs:
  build:
    name: Build Image and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate Docker Tag
        run: |
          if [[ '${{github.ref_type}}' == 'tag' ]]; then
            echo "DOCKER_TAG=${{github.ref_name}}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          fi
          
      - name: Run Docker Image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.AWS_SSH_HOST}}
          username: ${{secrets.AWS_SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            docker stop $(docker ps -aq)
            docker run -it -d -p 80:8080 ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_REPOSITORY}}:${{env.DOCKER_TAG}}
      - name: Wait for Docker Startup
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Check Website available
        run: |
          if ! curl --output /dev/null --silent --head --fail "http://spring-boot-xliff-example.alaugks.de/en/home"; then
            exit 1
          fi
