name: Push Docker Image to Docker Hub
run-name: Push Docker Image to Docker Hub [${{ github.ref_name }}]
on:
  workflow_dispatch:
jobs:
  build:
    name: Build Image and Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache local Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys: |
            ${{runner.os}}-maven-       

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '17'
          check-latest: true
          cache: 'maven'

      - name: Install & Run Tests
        run: |
          mvn clean install
          mvn test

      - name: Evaluate Docker Tag
        run: |
          if [[ '${{github.ref_type}}' == 'tag' ]]; then
            echo "DOCKER_TAG=${{github.ref_name}}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          platforms: linux/amd64,linux/arm64,windows/amd64
          push: true
          tags: ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_REPOSITORY}}:${{env.DOCKER_TAG}}
