name: Build and Push Docker Image to Docker Hub
run-name: Build and Push Docker Image to Docker Hub [${{ github.ref_name }}]
on:
  workflow_dispatch:
jobs:

  tests:
    name: Docker Build Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: "Build Docker Image"
        run: |
          docker compose up -d  

      - name: "SmokeTest"
        run: |
          sleep 20
          if ! curl --output /dev/null --silent --head --fail "http://127.0.0.1:8080/en/home"; then
            echo "SmokeTest failed"
            exit 1
          fi  

  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Set App Version
        run: |
          sed -i 's/###LOCAL###/${{github.ref_name}}/g' src/main/resources/application.properties

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          platforms: linux/amd64,linux/arm64,windows/amd64
          push: true
          tags: ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_REPOSITORY}}:${{github.ref_name}}
